<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FilterCriterion;
use Illuminate\Support\Facades\DB;

class FilterCriteriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $criteria = [
            // ====================================================================
            // 1. NGÂN HÀNG (BANKING) - 32 TIÊU CHÍ CHUẨN HÓA
            // ====================================================================
            [
                'id' => 'crit_cir_under_60_latest',
                'category' => 'Hiệu Quả Vận Hành & Chi Phí (CIR)',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ lệ Chi phí / Thu nhập (CIR) dưới 60% ở năm gần nhất',
                'field' => 'Tỷ lệ Chi phí / Thu nhập (CIR)',
                'mode' => 'threshold',
                'operator' => '<=',
                'value' => 0.60,
                'display_value' => '60%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 1
            ],
            [
                'id' => 'crit_cir_under_avg_latest',
                'category' => 'Hiệu Quả Vận Hành & Chi Phí (CIR)',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ lệ Chi phí / Thu nhập (CIR) dưới trung bình ngành ở năm gần nhất',
                'field' => 'Tỷ lệ Chi phí / Thu nhập (CIR)',
                'mode' => 'industry_avg_lower',
                'operator' => null,
                'value' => null,
                'display_value' => '< TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 2
            ],
            [
                'id' => 'crit_cir_under_avg_10y',
                'category' => 'Hiệu Quả Vận Hành & Chi Phí (CIR)',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ lệ Chi phí / Thu nhập (CIR) dưới trung bình ngành liên tiếp 10 năm',
                'field' => 'Tỷ lệ Chi phí / Thu nhập (CIR)',
                'mode' => 'industry_avg_lower',
                'operator' => null,
                'value' => null,
                'display_value' => '< TB Ngành (10 năm)',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 3
            ],
            [
                'id' => 'crit_cpkh_under_10_latest',
                'category' => 'Hiệu Quả Vận Hành & Chi Phí (CIR)',
                'industry' => 'NGAN_HANG',
                'name' => 'CPKH/Tổng thu nhập hoạt động dưới 10% ở năm gần nhất',
                'field' => 'CPKH/Tổng thu nhập hoạt động',
                'mode' => 'threshold',
                'operator' => '<=',
                'value' => 0.10,
                'display_value' => '10%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 4
            ],
            [
                'id' => 'crit_op_margin_above_avg_10y',
                'category' => 'Hiệu Quả Vận Hành & Chi Phí (CIR)',
                'industry' => 'NGAN_HANG',
                'name' => 'Biên lãi vận hành (trước DPRR) cao hơn trung bình ngành trong liên tiếp 10 năm',
                'field' => 'Biên lãi vận hành (trước DPRR)',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành (10 năm)',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 5
            ],
            [
                'id' => 'crit_pbt_margin_above_avg_10y',
                'category' => 'Hiệu Quả Vận Hành & Chi Phí (CIR)',
                'industry' => 'NGAN_HANG',
                'name' => 'Biên lợi nhuận trước thuế cao hơn trung bình ngành trong liên tiếp 10 năm',
                'field' => 'Biên lợi nhuận trước thuế',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành (10 năm)',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 6
            ],
            [
                'id' => 'crit_npat_margin_above_avg_latest',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Biên Lợi nhuận ST của CĐ công ty mẹ cao hơn trung bình ngành ở năm gần nhất',
                'field' => 'Biên Lợi nhuận ST của CĐ công ty mẹ',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 7
            ],
            [
                'id' => 'crit_npat_margin_above_avg_10y',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Biên Lợi nhuận ST của CĐ công ty mẹ cao hơn trung bình ngành liên tiếp 10 năm',
                'field' => 'Biên Lợi nhuận ST của CĐ công ty mẹ',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành (10 năm)',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 8
            ],
            [
                'id' => 'crit_growth_npat_positive_10y',
                'category' => 'Thanh Khoản, Nợ Vay & Dòng Tiền',
                'industry' => 'NGAN_HANG',
                'name' => 'Tăng trưởng lãi ròng sau CĐ thiểu số luôn là số dương liên tiếp 10 năm',
                'field' => 'Tăng trưởng lãi ròng sau CĐ thiểu số',
                'mode' => 'threshold',
                'operator' => '>',
                'value' => 0,
                'display_value' => '> 0 (Dương)',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 9
            ],
            [
                'id' => 'crit_roa_above_avg_latest',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ suất sinh lời trên Tổng Tài Sản (ROA) cao hơn trung bình ngành ở năm gần nhất',
                'field' => 'Tỷ suất sinh lời trên Tổng Tài Sản (ROA)',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 10
            ],
            [
                'id' => 'crit_roa_above_avg_10y',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ suất sinh lời trên Tổng Tài Sản (ROA) cao hơn trung bình ngành liên tiếp 10 năm',
                'field' => 'Tỷ suất sinh lời trên Tổng Tài Sản (ROA)',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành (10 năm)',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 11
            ],
            [
                'id' => 'crit_roa_above_1pct',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ suất sinh lời trên Tổng Tài Sản (ROA) từ 1% trở lên ở năm gần nhất',
                'field' => 'Tỷ suất sinh lời trên Tổng Tài Sản (ROA)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.01,
                'display_value' => '1.0%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 12
            ],
            [
                'id' => 'crit_de_under_10',
                'category' => 'Thanh Khoản, Nợ Vay & Dòng Tiền',
                'industry' => 'NGAN_HANG',
                'name' => 'Debt/Equity dưới 10 ở năm gần nhất',
                'field' => 'Debt/Equity',
                'mode' => 'threshold',
                'operator' => '<=',
                'value' => 10,
                'display_value' => '10.0',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 13
            ],
            [
                'id' => 'crit_de_under_avg_latest',
                'category' => 'Thanh Khoản, Nợ Vay & Dòng Tiền',
                'industry' => 'NGAN_HANG',
                'name' => 'Debt/Equity thấp hơn trung bình ngành ở năm gần nhất',
                'field' => 'Debt/Equity',
                'mode' => 'industry_avg_lower',
                'operator' => null,
                'value' => null,
                'display_value' => '< TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 14
            ],
            [
                'id' => 'crit_de_under_avg_10y',
                'category' => 'Thanh Khoản, Nợ Vay & Dòng Tiền',
                'industry' => 'NGAN_HANG',
                'name' => 'Debt/Equity thấp hơn trung bình ngành liên tiếp 10 năm',
                'field' => 'Debt/Equity',
                'mode' => 'industry_avg_lower',
                'operator' => null,
                'value' => null,
                'display_value' => '< TB Ngành (10 năm)',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 15
            ],
            [
                'id' => 'crit_roe_above_avg_latest',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ suất sinh lời trên Vốn CSH (ROE) cao hơn trung bình ngành ở năm gần nhất',
                'field' => 'Tỷ suất sinh lời trên Vốn CSH (ROE)',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 16
            ],
            [
                'id' => 'crit_roe_above_avg_10y',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ suất sinh lời trên Vốn CSH (ROE) cao hơn trung bình ngành liên tiếp 10 năm',
                'field' => 'Tỷ suất sinh lời trên Vốn CSH (ROE)',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành (10 năm)',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 17
            ],
            [
                'id' => 'crit_roe_15_10y',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ suất sinh lời trên Vốn CSH (ROE) đạt tối thiểu 15% liên tiếp 10 năm',
                'field' => 'Tỷ suất sinh lời trên Vốn CSH (ROE)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.15,
                'display_value' => '15.0%',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 18
            ],
            [
                'id' => 'crit_roe_20_10y',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ suất sinh lời trên Vốn CSH (ROE) đạt tối thiểu 20% liên tiếp 10 năm',
                'field' => 'Tỷ suất sinh lời trên Vốn CSH (ROE)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.20,
                'display_value' => '20.0%',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 19
            ],
            [
                'id' => 'crit_cfo_gt_npat_10y',
                'category' => 'Thanh Khoản, Nợ Vay & Dòng Tiền',
                'industry' => 'NGAN_HANG',
                'name' => 'Lưu chuyển tiền thuần từ HĐKD lớn hơn LNST của CĐ công ty mẹ liên tiếp 10 năm',
                'field' => 'Lưu chuyển tiền thuần từ hoạt động kinh doanh',
                'mode' => 'compare_fields',
                'operator' => '>',
                'value' => null,
                'display_value' => '> LNST CĐ mẹ',
                'compare_with_field' => 'Lợi nhuận sau thuế của cổ đông công ty mẹ',
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 20
            ],
            [
                'id' => 'crit_casa_above_avg_latest',
                'category' => 'Thanh Khoản, Nợ Vay & Dòng Tiền',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ lệ tiền gửi không kỳ hạn (CASA) cao hơn trung bình ngành ở năm gần nhất',
                'field' => 'Tỷ lệ tiền gửi không kỳ hạn (CASA)',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 21
            ],
            [
                'id' => 'crit_casa_above_avg_10y',
                'category' => 'Thanh Khoản, Nợ Vay & Dòng Tiền',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ lệ tiền gửi không kỳ hạn (CASA) cao hơn trung bình ngành liên tiếp 10 năm',
                'field' => 'Tỷ lệ tiền gửi không kỳ hạn (CASA)',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành (10 năm)',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 22
            ],
            [
                'id' => 'crit_npl_under_avg_latest',
                'category' => 'Chất Lượng Tài Sản & An Toàn Vốn',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ lệ nợ xấu (NPL) cuối năm dưới trung bình ngành ở năm gần nhất',
                'field' => 'Tỷ lệ nợ xấu (NPL) cuối năm',
                'mode' => 'industry_avg_lower',
                'operator' => null,
                'value' => null,
                'display_value' => '< TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 23
            ],
            [
                'id' => 'crit_npl_under_avg_10y',
                'category' => 'Chất Lượng Tài Sản & An Toàn Vốn',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ lệ nợ xấu (NPL) cuối năm dưới trung bình ngành liên tiếp 10 năm',
                'field' => 'Tỷ lệ nợ xấu (NPL) cuối năm',
                'mode' => 'industry_avg_lower',
                'operator' => null,
                'value' => null,
                'display_value' => '< TB Ngành (10 năm)',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 24
            ],
            [
                'id' => 'crit_nim_above_3_latest',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Biên lãi thuần (NIM) trên 3% năm gần nhất',
                'field' => 'Biên lãi thuần (NIM)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.03,
                'display_value' => '3.0%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 25
            ],
            [
                'id' => 'crit_nim_above_3_10y',
                'category' => 'Khả Năng Sinh Lời & NIM',
                'industry' => 'NGAN_HANG',
                'name' => 'Biên lãi thuần (NIM) trên 3% liên tiếp 10 năm',
                'field' => 'Biên lãi thuần (NIM)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.03,
                'display_value' => '3.0%',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 26
            ],
            [
                'id' => 'crit_car_above_10_latest',
                'category' => 'Chất Lượng Tài Sản & An Toàn Vốn',
                'industry' => 'NGAN_HANG',
                'name' => 'Hệ số an toàn vốn (CAR) trên 10% năm gần nhất',
                'field' => 'Hệ số an toàn vốn (CAR)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.10,
                'display_value' => '10%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 27
            ],
            [
                'id' => 'crit_car_above_10_10y',
                'category' => 'Chất Lượng Tài Sản & An Toàn Vốn',
                'industry' => 'NGAN_HANG',
                'name' => 'Hệ số an toàn vốn (CAR) trên 10% liên tiếp 10 năm',
                'field' => 'Hệ số an toàn vốn (CAR)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.10,
                'display_value' => '10%',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 28
            ],
            [
                'id' => 'crit_car_above_12_latest',
                'category' => 'Chất Lượng Tài Sản & An Toàn Vốn',
                'industry' => 'NGAN_HANG',
                'name' => 'Hệ số an toàn vốn (CAR) trên 12% năm gần nhất',
                'field' => 'Hệ số an toàn vốn (CAR)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.12,
                'display_value' => '12%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 29
            ],
            [
                'id' => 'crit_car_above_12_10y',
                'category' => 'Chất Lượng Tài Sản & An Toàn Vốn',
                'industry' => 'NGAN_HANG',
                'name' => 'Hệ số an toàn vốn (CAR) trên 12% liên tiếp 10 năm',
                'field' => 'Hệ số an toàn vốn (CAR)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.12,
                'display_value' => '12%',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 30
            ],
            [
                'id' => 'crit_llr_above_50_latest',
                'category' => 'Chất Lượng Tài Sản & An Toàn Vốn',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ lệ bao phủ nợ xấu (LLR Coverage) trên 50% ở năm gần nhất',
                'field' => 'Tỷ lệ bao phủ nợ xấu (LLR Coverage)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.50,
                'display_value' => '50%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 31
            ],
            [
                'id' => 'crit_llr_above_50_10y',
                'category' => 'Chất Lượng Tài Sản & An Toàn Vốn',
                'industry' => 'NGAN_HANG',
                'name' => 'Tỷ lệ bao phủ nợ xấu (LLR Coverage) trên 50% liên tiếp 10 năm',
                'field' => 'Tỷ lệ bao phủ nợ xấu (LLR Coverage)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.50,
                'display_value' => '50%',
                'compare_with_field' => null,
                'time_scope' => '10y_consecutive',
                'is_custom' => false,
                'sort_order' => 32
            ],

            // ====================================================================
            // 2. BẤT ĐỘNG SẢN (REAL ESTATE) - TIÊU CHÍ CHUẨN HÓA
            // ====================================================================
            [
                'id' => 'crit_bds_de_under_1_5',
                'category' => 'Cơ Cấu Vốn & An Toàn Nợ Vay BĐS',
                'industry' => 'BAT_DONG_SAN',
                'name' => 'Nợ vay/Vốn CSH dưới 1.5 lần ở năm gần nhất',
                'field' => 'Nợ vay/Vốn CSH',
                'mode' => 'threshold',
                'operator' => '<=',
                'value' => 1.50,
                'display_value' => '1.5 lần',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 101
            ],
            [
                'id' => 'crit_bds_de_under_avg_latest',
                'category' => 'Cơ Cấu Vốn & An Toàn Nợ Vay BĐS',
                'industry' => 'BAT_DONG_SAN',
                'name' => 'Nợ vay/Vốn CSH thấp hơn trung bình ngành BĐS ở năm gần nhất',
                'field' => 'Nợ vay/Vốn CSH',
                'mode' => 'industry_avg_lower',
                'operator' => null,
                'value' => null,
                'display_value' => '< TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 102
            ],
            [
                'id' => 'crit_bds_gross_margin_25',
                'category' => 'Hiệu Quả Sinh Lời & Định Giá',
                'industry' => 'BAT_DONG_SAN',
                'name' => 'Biên lợi nhuận gộp từ 25% trở lên ở năm gần nhất',
                'field' => 'Biên lợi nhuận gộp',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.25,
                'display_value' => '25%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 103
            ],
            [
                'id' => 'crit_bds_gross_margin_above_avg',
                'category' => 'Hiệu Quả Sinh Lời & Định Giá',
                'industry' => 'BAT_DONG_SAN',
                'name' => 'Biên lợi nhuận gộp cao hơn trung bình ngành ở năm gần nhất',
                'field' => 'Biên lợi nhuận gộp',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 104
            ],
            [
                'id' => 'crit_bds_cfo_pos_latest',
                'category' => 'Hàng Tồn Kho & Tiềm Năng Bán Hàng',
                'industry' => 'BAT_DONG_SAN',
                'name' => 'Dòng tiền từ HĐKD (CFO) dương ở năm gần nhất',
                'field' => 'Lưu chuyển tiền thuần từ hoạt động kinh doanh (CFO)',
                'mode' => 'threshold',
                'operator' => '>',
                'value' => 0,
                'display_value' => '> 0',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 105
            ],
            [
                'id' => 'crit_bds_roe_above_12',
                'category' => 'Hiệu Quả Sinh Lời & Định Giá',
                'industry' => 'BAT_DONG_SAN',
                'name' => 'Tỷ suất sinh lời trên Vốn CSH (ROE) từ 12% trở lên ở năm gần nhất',
                'field' => 'Tỷ suất sinh lời trên Vốn CSH (ROE)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.12,
                'display_value' => '12%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 106
            ],
            [
                'id' => 'crit_bds_pb_under_2',
                'category' => 'Hiệu Quả Sinh Lời & Định Giá',
                'industry' => 'BAT_DONG_SAN',
                'name' => 'Chỉ số P/B dưới 2.0 lần ở năm gần nhất',
                'field' => 'Chỉ số P/B',
                'mode' => 'threshold',
                'operator' => '<=',
                'value' => 2.0,
                'display_value' => '2.0',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 107
            ],

            // ====================================================================
            // 3. CHỨNG KHOÁN (SECURITIES) - TIÊU CHÍ CHUẨN HÓA
            // ====================================================================
            [
                'id' => 'crit_ck_margin_de_under_150',
                'category' => 'Quy Mô Margin & Tăng Trưởng Hoạt Động',
                'industry' => 'CHUNG_KHOAN',
                'name' => 'Tỷ lệ Dư nợ Margin/Vốn CSH dưới 150% ở năm gần nhất',
                'field' => 'Tỷ lệ Dư nợ Margin/Vốn CSH',
                'mode' => 'threshold',
                'operator' => '<=',
                'value' => 1.50,
                'display_value' => '150%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 201
            ],
            [
                'id' => 'crit_ck_cir_under_50',
                'category' => 'Hiệu Quả Vận Hành & CIR CTCK',
                'industry' => 'CHUNG_KHOAN',
                'name' => 'Tỷ lệ Chi phí / Thu nhập (CIR) dưới 50% ở năm gần nhất',
                'field' => 'Tỷ lệ Chi phí / Thu nhập (CIR)',
                'mode' => 'threshold',
                'operator' => '<=',
                'value' => 0.50,
                'display_value' => '50%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 202
            ],
            [
                'id' => 'crit_ck_cir_under_avg_latest',
                'category' => 'Hiệu Quả Vận Hành & CIR CTCK',
                'industry' => 'CHUNG_KHOAN',
                'name' => 'Tỷ lệ Chi phí / Thu nhập (CIR) dưới trung bình ngành ở năm gần nhất',
                'field' => 'Tỷ lệ Chi phí / Thu nhập (CIR)',
                'mode' => 'industry_avg_lower',
                'operator' => null,
                'value' => null,
                'display_value' => '< TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 203
            ],
            [
                'id' => 'crit_ck_roe_above_15',
                'category' => 'Sinh Lời Vốn CSH & Định Giá',
                'industry' => 'CHUNG_KHOAN',
                'name' => 'Tỷ suất sinh lời trên Vốn CSH (ROE) từ 15% trở lên ở năm gần nhất',
                'field' => 'Tỷ suất sinh lời trên Vốn CSH (ROE)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.15,
                'display_value' => '15%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 204
            ],
            [
                'id' => 'crit_ck_npat_margin_above_avg',
                'category' => 'Sinh Lời Vốn CSH & Định Giá',
                'industry' => 'CHUNG_KHOAN',
                'name' => 'Biên Lợi nhuận ST của CĐ công ty mẹ cao hơn trung bình ngành ở năm gần nhất',
                'field' => 'Biên Lợi nhuận ST của CĐ công ty mẹ',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 205
            ],
            [
                'id' => 'crit_ck_pb_under_1_5',
                'category' => 'Sinh Lời Vốn CSH & Định Giá',
                'industry' => 'CHUNG_KHOAN',
                'name' => 'Chỉ số P/B dưới 1.5 lần ở năm gần nhất',
                'field' => 'Chỉ số P/B',
                'mode' => 'threshold',
                'operator' => '<=',
                'value' => 1.5,
                'display_value' => '1.5',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 206
            ],

            // ====================================================================
            // 4. THÉP & VLXD (STEEL) - TIÊU CHÍ CHUẨN HÓA
            // ====================================================================
            [
                'id' => 'crit_thep_gross_margin_12',
                'category' => 'Biên Lợi Nhuận Gộp & Hiệu Quả Chu Kỳ',
                'industry' => 'THEP',
                'name' => 'Biên lợi nhuận gộp từ 12% trở lên ở năm gần nhất',
                'field' => 'Biên lợi nhuận gộp',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.12,
                'display_value' => '12%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 301
            ],
            [
                'id' => 'crit_thep_gross_margin_above_avg',
                'category' => 'Biên Lợi Nhuận Gộp & Hiệu Quả Chu Kỳ',
                'industry' => 'THEP',
                'name' => 'Biên lợi nhuận gộp cao hơn trung bình ngành Thép ở năm gần nhất',
                'field' => 'Biên lợi nhuận gộp',
                'mode' => 'industry_avg_higher',
                'operator' => null,
                'value' => null,
                'display_value' => '> TB Ngành',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 302
            ],
            [
                'id' => 'crit_thep_inv_turnover_above_3',
                'category' => 'Quản Trị Tồn Kho & Dòng Tiền CFO',
                'industry' => 'THEP',
                'name' => 'Vòng quay hàng tồn kho từ 3.0 vòng trở lên ở năm gần nhất',
                'field' => 'Vòng quay hàng tồn kho',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 3.0,
                'display_value' => '3.0 vòng',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 303
            ],
            [
                'id' => 'crit_thep_de_under_1',
                'category' => 'Đòn Bẩy Tài Chính & Định Giá Thép',
                'industry' => 'THEP',
                'name' => 'Nợ vay/Vốn CSH dưới 1.0 lần ở năm gần nhất',
                'field' => 'Nợ vay/Vốn CSH',
                'mode' => 'threshold',
                'operator' => '<=',
                'value' => 1.0,
                'display_value' => '1.0 lần',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 304
            ],
            [
                'id' => 'crit_thep_cfo_pos_latest',
                'category' => 'Quản Trị Tồn Kho & Dòng Tiền CFO',
                'industry' => 'THEP',
                'name' => 'Dòng tiền từ HĐKD (CFO) dương ở năm gần nhất',
                'field' => 'Lưu chuyển tiền thuần từ hoạt động kinh doanh (CFO)',
                'mode' => 'threshold',
                'operator' => '>',
                'value' => 0,
                'display_value' => '> 0',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 305
            ],
            [
                'id' => 'crit_thep_roe_above_15',
                'category' => 'Đòn Bẩy Tài Chính & Định Giá Thép',
                'industry' => 'THEP',
                'name' => 'Tỷ suất sinh lời trên Vốn CSH (ROE) từ 15% trở lên ở năm gần nhất',
                'field' => 'Tỷ suất sinh lời trên Vốn CSH (ROE)',
                'mode' => 'threshold',
                'operator' => '>=',
                'value' => 0.15,
                'display_value' => '15%',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 306
            ],
            [
                'id' => 'crit_thep_pb_under_1_5',
                'category' => 'Đòn Bẩy Tài Chính & Định Giá Thép',
                'industry' => 'THEP',
                'name' => 'Chỉ số P/B dưới 1.5 lần ở năm gần nhất',
                'field' => 'Chỉ số P/B',
                'mode' => 'threshold',
                'operator' => '<=',
                'value' => 1.5,
                'display_value' => '1.5',
                'compare_with_field' => null,
                'time_scope' => 'latest',
                'is_custom' => false,
                'sort_order' => 307
            ]
        ];

        DB::table('filter_criteria')->truncate();

        foreach ($criteria as $crit) {
            FilterCriterion::create($crit);
        }
    }
}

